USE master;
GO

DROP DATABASE IF EXISTS TTTEADB;

CREATE DATABASE TTTEADB;
GO

USE TTTEADB;
GO

CREATE TABLE [characters] (
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[name] VARCHAR(100)
);
GO

CREATE TABLE [users] (
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	[email] VARCHAR(250) UNIQUE NOT NULL,
	[name] VARCHAR(100) NOT NULL
);
GO

CREATE TABLE [quotes] (
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[quote_ep] VARCHAR(400) NOT NULL,
	[quote_season] INT NOT NULL,
	[quote_text] INT NOT NULL,
	[characterid] INT NOT NULL FOREIGN KEY REFERENCES [Characters](id) ON DELETE CASCADE
);
GO

CREATE TABLE [favourites] (
	[id] INT NOT NULL PRIMARY KEY,
	[quoteid] INT NOT NULL,
	[userid] INT NOT NULL,
	[date_favourited] DATE NOT NULL,
	CONSTRAINT [QT_FK] FOREIGN KEY ([quoteid]) REFERENCES [quotes]([id]) ON DELETE CASCADE,
	CONSTRAINT [UT_FK] FOREIGN KEY ([userid]) REFERENCES [users]([id]) ON DELETE CASCADE,
);
GO