USE master;
GO

DROP DATABASE IF EXISTS TTTEADB;

CREATE DATABASE TTTEADB;
GO

USE TTTEADB;
GO

CREATE TABLE [characters] (
	[id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[name] VARCHAR(100)
);
GO

CREATE TABLE [users] (
	[id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	[email] VARCHAR(250) UNIQUE NOT NULL,
	[name] VARCHAR(100) NOT NULL
);
GO

CREATE TABLE [quotes] (
	[id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[quote_ep] INT NOT NULL,
	[quote_season] INT NOT NULL,
	[quote_text] VARCHAR(400) NOT NULL,
	[characterid] BIGINT NOT NULL FOREIGN KEY REFERENCES [Characters](id) ON DELETE CASCADE
);
GO

CREATE TABLE [favourites] (
	[id] BIGINT NOT NULL PRIMARY KEY,
	[quoteid] BIGINT NOT NULL,
	[userid] BIGINT NOT NULL,
	[date_favourited] DATETIME NOT NULL,
	CONSTRAINT [QT_FK] FOREIGN KEY ([quoteid]) REFERENCES [quotes]([id]) ON DELETE CASCADE,
	CONSTRAINT [UT_FK] FOREIGN KEY ([userid]) REFERENCES [users]([id]) ON DELETE CASCADE,
);
GO