USE master;
GO

DROP DATABASE IF EXISTS TTTEADB;

CREATE DATABASE TTTEADB;
GO

USE TTTEADB;
GO

CREATE TABLE [Character] (
	CharacterID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CharacterName VARCHAR(100)
);
GO

CREATE TABLE [User] (
	UserID INT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	UserEmail VARCHAR(250) UNIQUE NOT NULL,
	UserName VARCHAR(100) NOT NULL,
	IsPremium BIT NOT NULL
);
GO

CREATE TABLE [Quote] (
	QuoteID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	QuoteText VARCHAR(400) NOT NULL,
	QuoteEpisode INT NOT NULL,
	QuoteSeason INT NOT NULL,
	CharacterID INT NOT NULL FOREIGN KEY REFERENCES [Character](CharacterID) ON DELETE CASCADE
);
GO

CREATE TABLE FavoriteQuote(
	QuoteID INT NOT NULL,
	UserID INT NOT NULL,
	DateFavorited DATE NOT NULL,
	CONSTRAINT FQ_PK PRIMARY KEY (QuoteID,UserID),
	CONSTRAINT [QT_FK] FOREIGN KEY (QuoteID) REFERENCES [Quote](QuoteID) ON DELETE CASCADE,
	CONSTRAINT [UT_FK] FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE,
);
GO